const path = require("path");
module.exports = {
    // 生成的文件存放目录
    folderPath: path.resolve(__dirname, "./小册"),
    // 小册链接(小册第一章的链接)
    bookLinks: ["https://juejin.cn/book/7347579913702293567/section/7360946625923317798"],
    // 是否合并小册pdf（依赖easy-pdf-merge，需java环境）
    isMerge: false,
    // 对象格式cookie
    cookieOjbs: [
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1729239345.534891,
            hostOnly: false,
            httpOnly: true,
            name: "uid_tt",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "a92e9a1fe54ecae1b4ecc8f74f6e1a15",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1729239345.534966,
            hostOnly: false,
            httpOnly: true,
            name: "uid_tt_ss",
            path: "/",
            sameSiteaaaa: "no_restriction",
            secure: true,
            session: false,
            storeId: null,
            value: "a92e9a1fe54ecae1b4ecc8f74f6e1a15",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1715837137.810146,
            hostOnly: false,
            httpOnly: false,
            name: "msToken",
            path: "/",
            sameSiteaaaa: "no_restriction",
            secure: true,
            session: false,
            storeId: null,
            value: "-NHWZSlNr_Vr36KOe1ZOGDDfDzJ5Hgr9j4tuxh-k8n33cEBYhyaGaMys5FKHci4FxcUdZkZZyROk8F7GQQVTJhqjuwl4e8SZUZnz1v0KIFEntN4nVTQEYo75yg0sgHI=",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1729239349.082792,
            hostOnly: false,
            httpOnly: true,
            name: "store-region",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "cn-sh",
        },
        {
            domain: "juejin.cn",
            expirationDateaaaa: 1716514111,
            hostOnly: true,
            httpOnly: false,
            name: "s_v_web_id",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "verify_lu69rgyr_yAvOpuOs_Cbfq_4OmM_AlQG_r6wMEbSYuq1k",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1729239345.53505,
            hostOnly: false,
            httpOnly: true,
            name: "sid_tt",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "41117f0a606f57053cf8fad5488675f6",
        },
        {
            domain: "juejin.cn",
            expirationDateaaaa: 1721716435.155111,
            hostOnly: true,
            httpOnly: false,
            name: "MONITOR_DEVICE_ID",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "480518da-7f1e-47ad-a57f-e985edbe175e",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1723008064,
            hostOnly: false,
            httpOnly: false,
            name: "_tea_utm_cache_586864",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "{%22utm_source%22:%22post_pay_page%22}",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1732263281.211274,
            hostOnly: false,
            httpOnly: false,
            name: "__tea_cookie_tokens_2608",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "%257B%2522web_id%2522%253A%25227291580046630913596%2522%252C%2522user_unique_id%2522%253A%25227291580046630913596%2522%252C%2522timestamp%2522%253A1697703281211%257D",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1729239345.535373,
            hostOnly: false,
            httpOnly: true,
            name: "ssid_ucp_v1",
            path: "/",
            sameSiteaaaa: "no_restriction",
            secure: true,
            session: false,
            storeId: null,
            value: "1.0.0-KDYyNjViNTAzMzMzMWM4YjlmMjU4ZDA2YjljNzJlZWNjNWMxOTgyNTUKFgjn9sDA_fWRBhC2y8OpBhiwFDgIQDgaAmxmIiA0MTExN2YwYTYwNmY1NzA1M2NmOGZhZDU0ODg2NzVmNg",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1732263346.288856,
            hostOnly: false,
            httpOnly: false,
            name: "_ga",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "GA1.2.82546422.1697703346",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1729239349.082868,
            hostOnly: false,
            httpOnly: true,
            name: "store-region-src",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "uid",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1723008065,
            hostOnly: false,
            httpOnly: false,
            name: "_tea_utm_cache_2018",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "{%22utm_source%22:%22post_pay_page%22}",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1732263346.822326,
            hostOnly: false,
            httpOnly: false,
            name: "_ga_S695FMNGPJ",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "GS1.2.1697703346.1.0.1697703346.60.0.0",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1729239345.535132,
            hostOnly: false,
            httpOnly: true,
            name: "sessionid",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "41117f0a606f57053cf8fad5488675f6",
        },
        {
            domain: "juejin.cn",
            expirationDateaaaa: 1715562108,
            hostOnly: true,
            httpOnly: false,
            name: "_jj_ext",
            path: "/",
            sameSiteaaaa: "strict",
            secure: true,
            session: false,
            storeId: null,
            value: "1",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1749792336.372063,
            hostOnly: false,
            httpOnly: false,
            name: "_tea_utm_cache_2608",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "{%22utm_source%22:%22post_pay_page%22}",
        },
        {
            domain: "juejin.cn",
            expirationDateaaaa: 1721716435.154614,
            hostOnly: true,
            httpOnly: false,
            name: "MONITOR_WEB_ID",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "2209f007-a758-421f-9c7a-c436c290c148",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1729239345.535215,
            hostOnly: false,
            httpOnly: true,
            name: "sessionid_ss",
            path: "/",
            sameSiteaaaa: "no_restriction",
            secure: true,
            session: false,
            storeId: null,
            value: "41117f0a606f57053cf8fad5488675f6",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1728807345.534811,
            hostOnly: false,
            httpOnly: true,
            name: "sid_guard",
            path: "/",
            sameSiteaaaa: null,
            secure: false,
            session: false,
            storeId: null,
            value: "41117f0a606f57053cf8fad5488675f6%7C1697703350%7C31536000%7CFri%2C+18-Oct-2024+08%3A15%3A50+GMT",
        },
        {
            domain: ".juejin.cn",
            expirationDateaaaa: 1729239345.535291,
            hostOnly: false,
            httpOnly: true,
            name: "sid_ucp_v1",
            path: "/",
            sameSiteaaaa: null,
            secure: true,
            session: false,
            storeId: null,
            value: "1.0.0-KDYyNjViNTAzMzMzMWM4YjlmMjU4ZDA2YjljNzJlZWNjNWMxOTgyNTUKFgjn9sDA_fWRBhC2y8OpBhiwFDgIQDgaAmxmIiA0MTExN2YwYTYwNmY1NzA1M2NmOGZhZDU0ODg2NzVmNg",
        },
    ],
};
