const path = require("path");
module.exports = {
    // 生成的文件存放目录
    folderPath: path.resolve(__dirname, "./小册"),
    // 小册链接(小册第一章的链接)
    bookLinks: ["https://juejin.cn/book/7050063811973218341/section/7050063812044685343"],
    // 是否合并小册pdf（依赖easy-pdf-merge，需java环境）
    isMerge: false,
    // 对象格式cookie
    cookieOjbs: [
        {
            "domain": ".juejin.cn",
            "x": 1729239345.534891,
            "hostOnly": false,
            "httpOnly": true,
            "name": "uid_tt",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "a92e9a1fe54ecae1b4ecc8f74f6e1a15"
        },
        {
            "domain": ".juejin.cn",
            "x": 1729239345.534966,
            "hostOnly": false,
            "httpOnly": true,
            "name": "uid_tt_ss",
            "path": "/",
            "v": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": null,
            "value": "a92e9a1fe54ecae1b4ecc8f74f6e1a15"
        },
        {
            "domain": ".juejin.cn",
            "x": 1704249135.909251,
            "hostOnly": false,
            "httpOnly": false,
            "name": "msToken",
            "path": "/",
            "v": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": null,
            "value": "WhNUNqF7nnXwZpwjikVcDjsez6vx3GjfjH45jp6BCVn0x5Hn4S3P5sPkK4ARrzSYzXn-FAwzHgqMOPFD0O6EJPMMXYBzyW2xyDimXayRQdU3k-mqu978j1nTXVyAAP0="
        },
        {
            "domain": ".juejin.cn",
            "x": 1729239349.082792,
            "hostOnly": false,
            "httpOnly": true,
            "name": "store-region",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "cn-sh"
        },
        {
            "domain": "juejin.cn",
            "x": 1705990406,
            "hostOnly": true,
            "httpOnly": false,
            "name": "s_v_web_id",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "verify_lpc87xyi_pdX9GQtg_UlLw_4vpG_9tYj_no0YUVeEWBVL"
        },
        {
            "domain": ".juejin.cn",
            "x": 1729239345.53505,
            "hostOnly": false,
            "httpOnly": true,
            "name": "sid_tt",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "41117f0a606f57053cf8fad5488675f6"
        },
        {
            "domain": ".juejin.cn",
            "x": 1732263281.211274,
            "hostOnly": false,
            "httpOnly": false,
            "name": "__tea_cookie_tokens_2608",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "%257B%2522web_id%2522%253A%25227291580046630913596%2522%252C%2522user_unique_id%2522%253A%25227291580046630913596%2522%252C%2522timestamp%2522%253A1697703281211%257D"
        },
        {
            "domain": ".juejin.cn",
            "x": 1729239345.535373,
            "hostOnly": false,
            "httpOnly": true,
            "name": "ssid_ucp_v1",
            "path": "/",
            "v": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": null,
            "value": "1.0.0-KDYyNjViNTAzMzMzMWM4YjlmMjU4ZDA2YjljNzJlZWNjNWMxOTgyNTUKFgjn9sDA_fWRBhC2y8OpBhiwFDgIQDgaAmxmIiA0MTExN2YwYTYwNmY1NzA1M2NmOGZhZDU0ODg2NzVmNg"
        },
        {
            "domain": ".juejin.cn",
            "x": 1732263346.288856,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_ga",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "GA1.2.82546422.1697703346"
        },
        {
            "domain": ".juejin.cn",
            "x": 1729239349.082868,
            "hostOnly": false,
            "httpOnly": true,
            "name": "store-region-src",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "uid"
        },
        {
            "domain": ".juejin.cn",
            "x": 1711420134,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_tea_utm_cache_2018",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "{%22utm_source%22:%22gold_browser_extension%22}"
        },
        {
            "domain": ".juejin.cn",
            "x": 1732263346.822326,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_ga_S695FMNGPJ",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "GS1.2.1697703346.1.0.1697703346.60.0.0"
        },
        {
            "domain": ".juejin.cn",
            "x": 1729239345.535132,
            "hostOnly": false,
            "httpOnly": true,
            "name": "sessionid",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "41117f0a606f57053cf8fad5488675f6"
        },
        {
            "domain": "juejin.cn",
            "x": 1704158232,
            "hostOnly": true,
            "httpOnly": false,
            "name": "_jj_ext",
            "path": "/",
            "v": "strict",
            "secure": true,
            "session": false,
            "storeId": null,
            "value": "1"
        },
        {
            "domain": ".juejin.cn",
            "x": 1738204133.995719,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_tea_utm_cache_2608",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "{%22utm_source%22:%22gold_browser_extension%22}"
        },
        {
            "domain": ".juejin.cn",
            "x": 1705902105,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_tea_utm_cache_4366",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "{%22utm_source%22:%221017tc%22}"
        },
        {
            "domain": ".juejin.cn",
            "x": 1708071345.534229,
            "hostOnly": false,
            "httpOnly": true,
            "name": "n_mh",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "EFg1_mBHQbgSgSf99DQS8qIA7qY3jFf9OAFGOWaDQQk"
        },
        {
            "domain": ".juejin.cn",
            "x": 1729239345.535215,
            "hostOnly": false,
            "httpOnly": true,
            "name": "sessionid_ss",
            "path": "/",
            "v": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": null,
            "value": "41117f0a606f57053cf8fad5488675f6"
        },
        {
            "domain": ".juejin.cn",
            "x": 1728807345.534811,
            "hostOnly": false,
            "httpOnly": true,
            "name": "sid_guard",
            "path": "/",
            "v": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "41117f0a606f57053cf8fad5488675f6%7C1697703350%7C31536000%7CFri%2C+18-Oct-2024+08%3A15%3A50+GMT"
        },
        {
            "domain": ".juejin.cn",
            "x": 1729239345.535291,
            "hostOnly": false,
            "httpOnly": true,
            "name": "sid_ucp_v1",
            "path": "/",
            "v": null,
            "secure": true,
            "session": false,
            "storeId": null,
            "value": "1.0.0-KDYyNjViNTAzMzMzMWM4YjlmMjU4ZDA2YjljNzJlZWNjNWMxOTgyNTUKFgjn9sDA_fWRBhC2y8OpBhiwFDgIQDgaAmxmIiA0MTExN2YwYTYwNmY1NzA1M2NmOGZhZDU0ODg2NzVmNg"
        }
    ]
};
